apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "plex"
spec:
  type: ClusterIP
  selector:
    app: plex
  ports:
    - name: plex
      port: 80
      targetPort: 32400
      protocol: TCP
